### ISSUE TITLE
Avoid to initialize a variable that is returned in the next line

### ISSUE THREAD

**Issue by avpaderno** [backdrop-contrib/examples#33]
Some functions contain code similar to the following.

```php
$result = array(
  '#markup' => check_plain($string),
);
return $result;
```

I thought it was done for a specific reason, but then I noticed the next function uses the following code.

```php
/**
 * Implements hook_autoload_info().
 */
function block_example_autoload_info() {
  return array(
    'BlockExample' => 'block_example.inc',
  );
}
```

Code that initializes a variable that is immediately returned should be changed to not use that variable, as `block_example_autoload_info()` does.

**Comment by avpaderno** [comment]
I also made the code more consistent about using an empty line before the `return` line.

**Comment by argiepiano** [comment]
While I generally agree with "economy of variables", often the use of superfluous variables serves two purposes:

1. Makes things more readable for human eyes (variable names are often a way to document what the content is)
2. Makes things easier to step-debug.

So, I'd keep these two things in mind when making all these changes. 

Things like `return $output . "</table>";` while it works, it's not very readable and not very conceptual. The concept here is that we are using $output as the content of the element we are theming. $output is built step by step. Why get rid of the last step when $output is assigned the closing tag, "just because we can"? 

Also things like 
```php
    return db_update('dbtng_example')
      ->fields($entry)
      ->condition('pid', $entry['pid'])
      ->execute();
  }
```

are harder to step-debug and comprehend than
```php 
$count = db_update('dbtng_example')
              ->fields($entry)
              ->condition('pid', $entry['pid'])
              ->execute(); 
return $count;
```

Someone reading the second code above would right await understand what's being returned (the count).

Anyway, I guess in the end it's a matter of personal preference, but given that this module is Examples for Developers, you want to make things as readable and debuggable as possible!

**Comment by avpaderno** [comment]
In the last example, there is already a comment saying what `db_update()` returns.

```php
// db_update()...->execute() returns the number of rows updated.
return db_update('dbtng_example')
  ->fields($entry)
  ->condition('pid', $entry['pid'])
  ->execute();
```

`return <expression>` is not harder to understand than `<variable> = <expression>`. It is probably more difficult to understand the chained method calls, but those are already used in the code. There are people who write code similar to the following, and then do not understand why the code does not work.

```php
$query = db_select('file_managed', 'f')
  ->condition('f.status', $status);
  ->addExpression('SUM(f.filesize)', 'filesize');

if (isset($uid)) {
  $query->condition('f.uid', $uid);
}
return $query->execute()->fetchField();
```

That does not mean chained method calls should be avoided.

I did not remove all the variables used in a function or replaced three assignments done to the same variable with a single assignment that is quite impossible to follow. I just replaced `$variable = function_call(); return $variable;` with `return function_call();`.

**Comment by avpaderno** [comment]
I changed back lines like `return $output . "</table>";` where `$output` is not initialized right before to return its value. (`return $output . "</table>";` was changed to `$output .= "</table>"; return $output;`.)

**Comment by docwilmot** [comment]
> Anyway, I guess in the end it's a matter of personal preference, but given that this module is Examples for Developers, you want to make things as readable and debuggable as possible!

Agreed with this.

**Comment by argiepiano** [comment]
I wholeheartedly agree with and support all your comments in the PR, @docwilmot. Even though the variables may be superfluous, they really fulfill the two criteria I mentioned above. Not only that, but they also follow more closely what's done in core.

**Comment by avpaderno** [comment]
There are few cases where the variable name is not much descriptive, but in those cases, it is sufficient to use a different variable name.

Backdrop core returns a variable value 2821 times out of 8030 times the `return` statement is used (compare the value printed by `git grep -n -E '^[[:space:]]*return \$[a-zA-Z_][a-zA-Z0-9_]*;$' | wc -l` with the value printed by `git grep -n -E '^[[:space:]]*return ' | wc -l`). That is irrelevant, though, as Backdrop core is not a set of example modules.  

I just wanted to avoid people would get into the habit of assigning the value to a variable only to return the variable on the very next line, but that should not be done at the expense of documenting the return value (which is more important in example modules).
